server:
 servlet:
   context-path: /EmployeePortalWithBoot
spring:
 datasource: 
   url: jdbc:mysql://localhost/employeeportal
   username: root
   password: 12345
   driver-class-name : com.mysql.jdbc.Driver
   type: org.apache.tomcat.jdbc.pool.DataSource
 
 mail:
    host: smtp.gmail.com
    port: 587
    username: jai.garg@metacube.com
    password: sytmgsxrihfpztbx
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com